<?php if (isset($this->success) && $this->success == true): ?>
    <p class="message"><?php print $this->successMessage; ?></p>
<?php endif; ?>

<?php require_once BASEPATH . '/views/month-rest.phtml'; ?>

<form action="<?php print $this->basepath; ?>/default/new" method="post">
    <?php print $this->translations->date; ?>
    <input type="text" name="date" value="<?php print $this->today; ?>" />
    <?php print $this->translations->shop; ?>
    <input type="text" name="shop" value="<?php print $this->mostUsedShop; ?>" maxlength="255" />
    <?php print $this->translations->amount; ?> (<?php print $this->currency; ?>)
    <input type="text" name="amount" value="0.00" />
    <?php print $this->translations->comment; ?>
    <input type="text" name="comment" value="" maxlength="255" />
    <input type="submit" value="<?php print $this->translations->insert; ?>" />
</form>