<?php if (!$this->monthExists): ?>
<div class="message">
    <p><?php print $this->translations->month->notexisting; ?></p>
    <p>
        <form action="<?php print $this->basepath; ?>/month/createlimit" method="post">
        	<input type="hidden" name="forward-controller" value="<?php print $this->controllerName; ?>" />
        	<input type="hidden" name="forward-action" value="<?php print $this->actionName; ?>" />
        	<?php print $this->translations->limit . ' (' . $this->currency . ')'; ?>:
        	<input type="text" name="limit" value="<?php print $this->monthLimit; ?>" />
        	<input type="hidden" name="month" value="<?php print $this->month; ?>" />
        	<input type="submit" value="<?php print $this->translations->insert; ?>" />
        </form>
    </p>
</div>
<?php else:?>
<div class="month-rest month-rest-<?php print((int)($this->month->rest > 0)); ?>">
    <p class="rest">
        <b><?php print $this->translations->month->rest . ' ' . $this->month->getNameAndYear() ?>:</b>
        <?php print $this->month->rest; ?>
        <?php print $this->currency; ?>
    </p>

    <p class="traffic-light">
        <span class="green"></span>
        <span class="yellow"></span>
        <span class="red"></span>
    </p>
</div>
<?php endif; ?>