<!DOCTYPE html>
<html>
<head> 
    <title>ShoppingControl</title>
    <link rel="icon" type="image/x-icon" href="<?php print URLPATH; ?>/img/shopping-control.ico" />
    <link rel="apple-touch-icon" type="image/x-icon" href="<?php print URLPATH; ?>/img/shopping-control.ico" />
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <base href="<?php print $this->basepath; ?>/" />
    <link rel="stylesheet" type="text/css" href="<?php print URLPATH; ?>/css/default.css?<?php print $this->cachebuster; ?>" />
    <script type="text/javascript" src="<?php print URLPATH; ?>/js/jquery.js?<?php print $this->cachebuster; ?>"></script>
</head>

<body>
<div class="content-wrapper">
    <div class="header">
        <?php if ($this->showNavigation) { ?>
            <img class="navigation-trigger active" src="img/list.png" alt="<?php print $this->translations->navigation->title; ?>" />
            <img class="navigation-trigger" src="img/list-active.png" alt="<?php print $this->translations->navigation->title; ?>" />
        <?php } ?>
        <h1 class="name">
            <a href="<?php print URLPATH; ?>/">
                ShoppingControl <?php print $this->version ?>
            </a>
        </h1>
        <?php if (!empty($this->loggedInUser)) { ?>
        <a href="<?php print URLPATH; ?>/" class="logininfo">
            <b><?php print $this->translations->login->loggedinas; ?>:</b>
            <?php print $this->loggedInUser; ?>
        </a>
        <?php } ?>

        <?php if ($this->showNavigation) { ?>
            <div class="navigation">
                <a href="<?php print URLPATH; ?>/">
                    <img src="img/icon-add.png" width="30" height="30" alt="" />
                    <span><?php print $this->translations->navigation->new; ?></span>
                </a>
                <a href="<?php print URLPATH; ?>/overview/currentmonth">
                    <img src="img/icon-calendar.png" width="30" height="30" alt="" />
                    <span><?php print $this->translations->navigation->current; ?></span>
                </a>
                <a href="<?php print URLPATH; ?>/overview">
                    <img src="img/icon-books.png" width="30" height="30" alt="" />
                    <span><?php print $this->translations->navigation->overview; ?></span>
                </a>
                <a href="<?php print URLPATH; ?>/admin">
                    <img src="img/icon-preferences.png" width="30" height="30" alt="" />
                    <span><?php print $this->translations->navigation->admin; ?></span>
                </a>
                <a href="<?php print URLPATH; ?>/logout">
                    <img src="img/icon-padlock.png" width="30" height="30" alt="" />
                    <span><?php print $this->translations->logout->logout; ?></span>
                </a>
            </div>
        <?php } ?>
    </div>

    <div class="content">
        <?php print $this->layout()->content; ?>
    </div>
    <div class="copyright">
        Shopping Control - Version <?php print $this->version ?><br />
        &copy; 2014 <a href="http://www.github.com/djungowski">Dominik Jungowski</a><br />
        Background: &copy; <a href="https://www.flickr.com/photos/naomiyaki/4583474627/">Naomi Rubin</a>
    </div>
</div>

<script type="text/javascript">
    $('.navigation-trigger').click(function() {
        $('.navigation').slideToggle(200);
        $('.navigation-trigger').toggleClass('active');
    });
</script>
</body>
</html>