<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"> 
<head> 
    <title>ShoppingControl</title>
    <link rel="icon" type="image/x-icon" href="<?php print URLPATH; ?>/img/shopping-control.ico" />
    <link rel="apple-touch-icon" type="image/x-icon" href="<?php print URLPATH; ?>/img/shopping-control.ico" />
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <base href="<?php print $this->basepath; ?>/" />
    <link rel="stylesheet" type="text/css" href="<?php print URLPATH; ?>/css/default.css?<?php print $this->cachebuster; ?>" />
    <script type="text/javascript" src="<?php print URLPATH; ?>/js/jquery.js?<?php print $this->cachebuster; ?>"></script>
</head>

<body>
<div class="content-wrapper">
    <div class="header">
        <h1 class="name">
            ShoppingControl <?php print $this->version ?>
        </h1>
        <?php if (!empty($this->loggedInUser)) { ?>
        <span class="logininfo">
            <b><?php print $this->translations->login->loggedinas; ?>:</b>
            <?php print $this->loggedInUser; ?>
        </span>
        <?php } ?>
    </div>
    <?php if ($this->showNavigation) { ?>
    <div class="navigation">
        <a href="<?php print URLPATH; ?>/">
            <?php print $this->translations->navigation->new; ?>
        </a>
        <a href="<?php print URLPATH; ?>/overview/currentmonth">
            <?php print $this->translations->navigation->current; ?>
        </a>
    </div>
    <?php } ?>

    <div class="content">
        <?php print $this->layout()->content; ?>
    </div>
    <?php if ($this->showNavigation) { ?>
    <div class="navigation">
        <a href="<?php print URLPATH; ?>/overview">
            <?php print $this->translations->navigation->overview; ?>
        </a>
        <a href="<?php print URLPATH; ?>/admin">
            <?php print $this->translations->navigation->admin; ?>
        </a>
        <a href="<?php print URLPATH; ?>/logout">
            <?php print $this->translations->logout->logout; ?>
        </a>
    </div>
    <?php } ?>
    <div class="copyright">
        Shopping Control - Version <?php print $this->version ?><br />
        &copy; 2012 <a href="http://www.github.com/djungowski">Dominik Jungowski</a>
    </div>
</div>
</body>
</html>