<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"> 
<head> 
    <title>ShoppingControl <?php print $this->version ?></title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <base href="<?php print $this->basepath; ?>/" />
    <link rel="stylesheet" type="text/css" href="<?php print URLPATH; ?>/css/default.css" />
    <!-- declared here since external stylesheet seem to ignore the base tag settings -->
    <style type="text/css">
        a {
        	background: transparent url('<?php print URLPATH; ?>/img/listArrow.png') no-repeat right 50%;
        }
    </style>
</head>

<body>
<div class="navigation">
    <a href="<?php print URLPATH; ?>/">
        <?php print $this->translations->navigation->new; ?>
    </a>
    <a href="<?php print URLPATH; ?>/overview/currentmonth">
        <?php print $this->translations->navigation->current; ?>
    </a>
</div>

<div class="content">
    <?php print $this->layout()->content; ?>
</div>
<div class="navigation">
    <a href="<?php print URLPATH; ?>/overview">
        <?php print $this->translations->navigation->overview; ?>
    </a>
    <a href="<?php print URLPATH; ?>/">
        <?php print $this->translations->navigation->admin; ?>
    </a>
</div>
<div class="copyright">
    Shopping Control <?php print $this->version ?> -
    &copy; 2010 Dominik Jungowski
</div>
</body>
</html>