<table class="overview" cellspacing="0">
	<tr>
		<th><?php print $this->translations->month->name; ?></th>
		<th><?php print $this->translations->limit; ?></th>
		<th><?php print $this->translations->spent; ?></th>
		<th><?php print $this->translations->rest; ?></th>
	</tr>
	<?php $i = 0; ?>
    <?php foreach ($this->years as $year => $months): ?>
    <tr>
    	<td colspan="4" class="year">
    	        <?php print($year); ?>
        </td>
    </tr>
    <?php foreach ($months as $key => $month): ?>
    <tr class="month-<?php print($month->month); if ($i > 0) { print(" hidden"); } ?>">
    	<td>
    		<a href="<?php print $month->getOverviewLink(); ?>">
    	        <?php print($month->__toString()); ?>
	        </a>
        </td>
    	<td>
    		<a href="<?php print $month->getOverviewLink(); ?>">
    		    <?php print($month->limit); ?>
	    	</a>
	    </td>
    	<td>
    		<a href="<?php print $month->getOverviewLink(); ?>">
    	        <?php print($month->spent()) ?>
	        </a>
        </td>
    	<td>
    		<a href="<?php print $month->getOverviewLink(); ?>">
    	        <?php print($month->getRest()); ?>
	        </a>
        </td>
    </tr>
    <?php endforeach; ?>
    <?php $i++; ?>
    <?php endforeach; ?>
</table>