<script type="text/javascript" src="<?php print URLPATH; ?>/js/plugins/jquery.monthtoggle.js?<?php print $this->cachebuster; ?>"></script>
<table class="overview" cellspacing="0">
	<tr>
		<th><?php print $this->translations->month->name; ?></th>
		<th><?php print $this->translations->limit; ?></th>
		<th class="amount"><?php print $this->translations->spent; ?></th>
		<th class="amount"><?php print $this->translations->rest; ?></th>
	</tr>
	<?php $i = 0; ?>
    <?php foreach ($this->years as $year => $months): ?>
        <tr>
        	<td colspan="4" class="year <?php print($year); ?>">
        	        <?php print($year); ?>
        	        <?php $arrow_direction = 'left'; if ($i == 0) { $arrow_direction = 'down'; }?>
        	        <img class="<?php print $arrow_direction; ?>" src="<?php print URLPATH; ?>/img/arrow_<?php print $arrow_direction; ?>.png" />
            </td>
        </tr>
        <?php foreach ($months as $key => $month): ?>
            <tr class="month-<?php print($month->getYear()); if ($i > 0) { print(" hidden"); } ?>">
            	<td>
            		<a href="<?php print $month->getOverviewLink(); ?>">
            	        <?php print($month->__toString()); ?>
        	        </a>
                </td>
            	<td>
            		<a href="<?php print $month->getOverviewLink(); ?>">
            		    <?php print($month->limit  . $this->currency); ?>
        	    	</a>
        	    </td>
            	<td class="amount">
            		<a href="<?php print $month->getOverviewLink(); ?>">
            	        <?php print($month->spent() . $this->currency) ?>
        	        </a>
                </td>
            	<td class="amount">
            		<a href="<?php print $month->getOverviewLink(); ?>">
            	        <?php print($month->getRest() .  $this->currency); ?>
        	        </a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php $i++; ?>
    <?php endforeach; ?>
    <script type="text/javascript">
    $('.year').monthtoggle();
    </script>
</table>