<h2 class="monthname">
	<?php print($this->monthName); ?>
</h2>
<script type="text/javascript" src="<?php print URLPATH; ?>/js/plugins/jquery.purchaseeditor.js?<?php print $this->cachebuster; ?>"></script>
<div class="edit-purchases-buttons">
    <a href="#" class="edit-purchases edit">
    	<?php print $this->translations->edit; ?>
    </a>
    <a href="#" class="edit-purchases delete">
    	<?php print $this->translations->delete; ?>
    </a>
    <a href="#" class="edit-purchases cancel">
    	<?php print $this->translations->cancel; ?>
    </a>
</div>
<div class="floating-correction"></div>

<form action="<?php print URLPATH; ?>/purchase/delete" method="post" id="edit-purchases-form">
<table class="overview" cellspacing="0">
	<tr>
		<th class="delete-purchase">&nbsp;</th>
		<th class="date">
		    <?php print $this->translations->date; ?>
        </th>
        <th class="shop">
		    <?php print $this->translations->shop->name; ?>
        </th>
		<th class="amount"><?php print $this->translations->amount; ?></th>
	</tr>
    <?php foreach ($this->purchases as $purchase): ?>
    <tr class="purchase">
    	<td class="delete-purchase">
    		<input type="checkbox" name="purchase_id[]" value="<?php print($purchase['purchase_id']); ?>" />
    	</td>
    	<td class="date">
    	    <?php print($purchase['date']); ?>
        </td>
        <td class="shop">
    	    <?php print($purchase['name']); ?>
    	    <?php if (!empty($purchase['comment'])): ?>
            <img class="comment-toggle" src="<?php print URLPATH; ?>/img/icon-info-14px.png" />
            <p class="comment">
                <strong><?php print $this->translations->comment; ?>:</strong>
                <br />
                <?php print($purchase['comment']); ?>
            </p>
    	    <?php endif; ?>
	    </td>
    	<td class="amount"><?php print($purchase['amount'] . ' ' . $this->currency); ?></td>
    </tr>
    <?php endforeach; ?>
    <tr>
    	<td class="delete-purchase total">&nbsp;</td>
    	<td class="total" colspan="2"><?php print($this->translations->spent); ?></td>
    	<td class="amount total"><?php print($this->spent . ' ' . $this->currency); ?></td>
    </tr>
</table>
</form>

<div class="edit-purchases-buttons">
    <a href="#" class="edit-purchases edit">
    	<?php print $this->translations->edit; ?>
    </a>
    <a href="#" class="edit-purchases delete">
    	<?php print $this->translations->delete; ?>
    </a>
    <a href="#" class="edit-purchases cancel">
    	<?php print $this->translations->cancel; ?>
    </a>
</div>
<div class="floating-correction"></div>

<script type="text/javascript">
$('.edit-purchases-buttons').purchaseeditor({
    safetyQuestion: '<?php print $this->translations->question->deletepurchase; ?>',
    purchaseClass: 'purchase'
});

$('tr').click(function() {
    if ($('.edit-purchases.delete').is(':visible')) {
        return;
    }
    var tr = $(this);
    var comment = tr.find('.comment');
    if (comment.length > 0) {
        comment.slideToggle(200);
        tr.toggleClass('comment-open');
    }
})
</script>